### ISSUE TITLE
pre-trained face segmentation model

### ISSUE THREAD

**Issue by fanfanda** [yiyuan1991/3D-Face-GCNs#2]
Is there any plan to public pre-trained face segmentation model? We notice that the model comes from paper(Face-to-parameter translation for game character auto-creation) in your FuxiCV work. However, it's not public available. Can you kindly public the model?

**Comment by HOMGH** [comment]
@FuxiCV  Would you please share your pretrained face segmentation model?
Also it seems that a "FaceReconModel.pb" is also needed to be in data folder. right? What is that?

**Comment by FuxiCV** [comment]
There are many excellent face segmentation networks in the community, for example, https://github.com/zllrunning/face-parsing.PyTorch is implemented in PyTorch and can be easily integrated into our code.

**Comment by fanfanda** [comment]
Thanks ~

**Comment by HOMGH** [comment]
> There are many excellent face segmentation networks in the community, for example, https://github.com/zllrunning/face-parsing.PyTorch is implemented in PyTorch and can be easily integrated into our code.

@FuxiCV  
Hi, Thank you for introducing this segmentation model, but it actually is a face parsing algorithm. However we only need the face and non-face regions. By putting the number of classes to 2, the code doesn't work and in other words can't produce a binary map for face. Would you please share the model of **torch_FaceSegment_300.pkl** which you used in your code, so that the result we get would be close to yours.
Thank you.

**Comment by cyjouc** [comment]
hi,can you share the torch_FaceSegment_300.pkl  with me?
